version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "a01sa01to"
    labels:
      - "dependencies"
    groups:
      all:
        patterns:
          - '*'

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "a01sa01to"
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/audit-forked-sites"
    schedule:
      interval: "weekly"
    reviewers:
      - "a01sa01to"
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/auto-i18n"
    schedule:
      interval: "weekly"
    reviewers:
      - "a01sa01to"
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/auto-tweet"
    schedule:
      interval: "weekly"
    reviewers:
      - "a01sa01to"
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/generate_datajson"
    schedule:
      interval: "weekly"
    reviewers:
      - "a01sa01to"
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/ogp_invalidator"
    schedule:
      interval: "weekly"
    reviewers:
      - "a01sa01to"
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/ui-test"
    schedule:
      interval: "weekly"
    reviewers:
      - "a01sa01to"
    labels:
      - "dependencies"
