version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "a01sa01to"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "a01sa01to"
    labels:
      - "dependencies"
    versioning-strategy: lockfile-only

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "a01sa01to"
    labels:
      - "dependencies"
    versioning-strategy: lockfile-only
