# 毎日0,6,12,18時に元Projectと同期する
name: Auto Sync

on:
  schedule:
    - cron: '0 3,9,15,21 * * *'

jobs:
  auto-sync:
    name: Sync
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GHAC_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: upstream
      - name: Add remote
        run: 'git remote add upstream https://github.com/tokyo-metropolitan-gov/covid19.git'
      - name: Fetch
        run: git fetch upstream
        if: ${{ always() }}
      - name: Merge
        run: git merge upstream/master
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GHAC_TOKEN }}
          branch: upstream