name: Check Statuses of Forked Sites

on:
  schedule:
    - cron: '0 0 1 * *'

  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-22.04

    steps:
      - name: Switch to the development branch
        uses: actions/checkout@v3
        with:
          ref: development

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: audit-forked-sites

      - name: Run scripts
        run: |
          python ./audit-forked-sites/check_status.py

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update FORKED_SITES.md
          title: Update FORKED_SITES.md
          labels: auto_merge
          branch-suffix: 'short-commit-hash'
