name: danger
on:
  - pull_request
jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '16.13.0'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --prefer-offline
      - name: Run Danger
        run: yarn danger:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
