name: danger
on:
  - pull_request
jobs:
  danger:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4.0.0
        with:
          node-version-file: ./.node-version
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --prefer-offline
      - name: Run Danger
        run: yarn danger:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
