name: Development Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - development
    paths-ignore:
      - 'auto-i18n/result.csv'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Setup Node
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16.13.0'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn run test
      - name: Generate for dev
        run: yarn run generate:dev --fail-on-page-error
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: dev-deploy

  ogp_build:
    name: OGP Build
    needs: deploy
    runs-on: macos-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/checkout@v2.4.0
        with:
          ref: dev-deploy
      - name: Install selenium with pip
        run: pip3 install selenium
      - name: Take screenshot
        run: (python3 -m http.server --directory ./ 8000 &)  ; python3 ./ui-test/ogp_screenshot.py
      - name: Upload screenshot
        uses: actions/upload-artifact@v1
        with:
          name: ogp
          path: ogp
  ogp_upload:
    name: OGP Upload
    needs: ogp_build
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/checkout@v2.4.0
        with:
          ref: dev-deploy
      - name: Download ogp images
        uses: actions/download-artifact@v1
        with:
          name: ogp
      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add ogp
          git commit -m "Add OGP changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev-deploy