name: Auto-i18n Generator

on:
  workflow_dispatch:
  push:
    branches:
      - development
    paths-ignore:
      - 'auto-i18n/result.csv'

jobs:
  i18n-builder:
    if: false == contains(github.event.commits[0].message, 'Update assets/locales/ja.json')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout development branch
        uses: actions/checkout@v3
        with:
          ref: development
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: python i18n_generator.py
        working-directory: auto-i18n
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.14.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update assets/locales/ja.json
          title: Update translation files
          labels: auto_merge
          branch-suffix: 'short-commit-hash'
