name: Pull Request Labeler

on:
  - pull_request
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Label for Transifex
      env:
        GITHUB_CONTEXT: ${{ toJson(github.actor) }}
      run: echo "$GITHUB_CONTEXT"
