name: Pull Request Labeler

on:
  - pull_request
jobs:
  triage:
    runs-on: ubuntu-22.04
    steps:
      - name: Label for Transifex
        if: github.actor == 'transifex-integration[bot]' && !endsWith(github.event.pull_request.title, '[manual sync]')
        uses: actions/labeler@v4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
