name: Automatic pull request review
on: [pull_request]
jobs:
  automate-pullrequest-review:
    runs-on: ubuntu-latest
    steps:
      - name: Approve pull request
        if: contains(github.event.pull_request.labels.*.name, 'dependencies')
        uses: andrewmusgrave/automatic-pull-request-review@0.0.5
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          event: APPROVE
          body: ''