name: production deploy

on:
  pull_request:
    branches:
      - development

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Run eslint with reviewdog
        uses: reviewdog/action-eslint@v1.0.0
          with:
            github_token: ${{ secrets.github_token }}
            reporter: github-pr-review
            eslint_flags: './**/*.{js,ts,vue}'