name: OGP Builder

on:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install --frozen-lockfile
      - run: yarn run test
      - run: yarn run generate:deploy
      - run: pip install selenium
      - run: (python -m http.server --directory ./dist 8000 &)  ; python ./ui-test/ogp_screenshot.py
      - name: Upload screenshot
        uses: actions/upload-artifact@v1
        with:
          name: ogps
          path: ogps
      - run: Get-ChildItem "ogps" | Select Name, DirectoryName, LastWriteTime,FulLName | Sort LastWriteTime -Descending | Select -First 2 | Select -ExpandProperty FullName | Copy-Item -Destination static
      - run: git checkout -b ogp
      - run: git status
      - run: SET DATETIME=%DATE:~0,4%-%DATE:~5,2%-%DATE:~8,2%%TIME:~0,8%
      - run: git add -u
      - run: git config --global user.email "yasu@users.noreply.github.com"
      - run: git config --global user.name "GDP Builder"
      - run: git commit -m "Generated OGP images at ${%DATETIME%}"
